### ISSUE TITLE
The scanner is not detecting the edges and enter in infinite loop

### ISSUE THREAD

**Issue by RitanMihai** [ubidreams/react-native-document-scanner#5]
I tried on this picture, but apparently it doesn't work on anything, not even on a card like the one in the example ...

![d9b4d64f-53fb-44f7-86b7-88c4ad1d5b56](https://user-images.githubusercontent.com/38959302/84427049-f3614c80-ac2c-11ea-82e2-5b5010b24575.jpg)

`Error: null is not an object (evaluating 'RNDocumentScanner.detectEdges')  `

![Issuse](https://user-images.githubusercontent.com/38959302/84426813-86e64d80-ac2c-11ea-811d-ee4294d3e5c7.PNG)

My package.json:

```
 "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-document-scanner": "^1.4.2",
     ...
},
  "devDependencies": {
    "@babel/core": "7.8.7",
    "@babel/preset-flow": "^7.9.0",
    "@babel/runtime": "7.8.7",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.8.0",
    "flow-bin": "^0.125.1",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.4",
    "react-test-renderer": "16.9.0"
  },
```

**Comment by rmarquois** [comment]
Hello, thanks for your feedback.
I think this bug is due to the fact that this library is not yet compatible with RN > 0.59.

You can test this workaround (by adding manually the package) :
```
    @Override
    protected List<ReactPackage> getPackages() {
        @SuppressWarnings("UnnecessaryLocalVariable")
        List<ReactPackage> packages = new PackageList(this).getPackages();
        // Packages that cannot be autolinked yet can be added manually here, for example:
        packages.add(new RNDocumentScannerPackage());
        return packages;
    }
```

I will fix this soon. PR are welcome !

**Comment by RitanMihai** [comment]
> Hello, thanks for your feedback.
> I think this bug is due to the fact that this library is not yet compatible with RN > 0.59.
> 
> You can test this workaround (by adding manually the package) :
> 
> ```
>     @Override
>     protected List<ReactPackage> getPackages() {
>         @SuppressWarnings("UnnecessaryLocalVariable")
>         List<ReactPackage> packages = new PackageList(this).getPackages();
>         // Packages that cannot be autolinked yet can be added manually here, for example:
>         packages.add(new RNDocumentScannerPackage());
>         return packages;
>     }
> ```
> 
> I will fix this soon. PR are welcome !

**Solution**
When I tried your solution (to add manually) I realized that I forgot to import `com.ubidreams.RNDocumentScanner.RNDocumentScannerPackage;`

**Other problem**
It does not detect very well, in my case (groceries receipt) I would say 30% of the time detects well, otherwise a square in the middle of the screen or a "dot".

In the case of the "dot", the adjustment points can no longer be moved. I'll come back with details on this issue after a few more tests
